FROM docker.io/library/golang:1.22.0-bullseye AS build

ARG VERSION
ENV VERSION $VERSION
WORKDIR /work

# Copy the source
COPY . ./
COPY go.sum ./
COPY go.mod ./
RUN go mod download

RUN CGO_ENABLED=1 GO111MODULE=on go build -ldflags "-X main.kleidiVersion=$VERSION" -a -installsuffix cgo cmd/kleidi/main.go

FROM quay.io/centos/centos:stream9-minimal

LABEL org.opencontainers.image.source=https://github.com/beezy-dev/kleidi 
LABEL org.opencontainers.image.title="Kleidi - Kubernetes KMS Plugin for Vault" 
LABEL org.opencontainers.image.vendor="beeyz.dev" 
LABEL org.opencontainers.image.licenses="Apache-2.0" 
LABEL org.opencontainers.image.description="Kleidi is an open-source Kubernetes Plugin supporting multiple KMS services." 
LABEL org.opencontainers.image.documentation="https://beezy.dev/kleidi/"

COPY --from=build ./work/main ./kleidi-kms-plugin

ENTRYPOINT [ "./kleidi-kms-plugin" ]
