kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-kleidi
nodes:
- role: worker
  image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
- role: control-plane
  image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
  extraMounts:
    - hostPath: platform/encryption
      containerPath: /etc/kubernetes/encryption
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        encryption-provider-config: "/etc/kubernetes/encryption/configuration.yaml"
        encryption-provider-config-automatic-reload: "true"
      extraVolumes:
        - name: "encryption"
          hostPath: /etc/kubernetes/encryption/configuration.yaml
          mountPath: /etc/kubernetes/encryption/configuration.yaml
          readOnly: false
          pathType: File
        - name: "kleidi"
          hostPath: /etc/kubernetes/encryption/softhsm-config.json
          mountPath: /etc/kubernetes/encryption/softhsm-config.json
          readOnly: false
          pathType: File