apiVersion: v1
kind: Pod
metadata:
  name: kleidi-provider
  namespace: kube-system
  labels:
    tier: control-plane
    component: kleidi-provider
spec:
  # hostNetwork: true is required because the plugin is run as a static pod
  # on the control plane node and needs to run before the CNI plugins are initialized.
  hostNetwork: true
  initContainers:
  - args:
    - |
      #!/bin/sh
      set -e
      set -x

      # if token exists, skip initialization
      if [ $(ls -1 /opt/softhsm/tokens | wc -l) -ge 1 ]; then
        echo "Skipping initialization of softhsm"
        exit 0
      fi

      mkdir -p /var/lib/softhsm/tokens
      apk add --update --no-cache ca-certificates jq
      apk add --no-cache ccid opensc softhsm
      
      cat /opt/softhsm/config.json
      TOKEN_LABEL=$(jq -r '.tokenLabel' /opt/softhsm/config.json)
      PIN=$(jq -r '.pin' /opt/softhsm/config.json)
      MODULE_PATH=$(jq -r '.path' /opt/softhsm/config.json)

      softhsm2-util --init-token --free --label $TOKEN_LABEL --pin $PIN --so-pin $PIN
      pkcs11-tool --module $MODULE_PATH --keygen --key-type aes:32 --pin $PIN --token-label $TOKEN_LABEL --label kleidi-test
    command:
    - /bin/sh
    - -c
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    name: init-kleidi-provider
    volumeMounts:
    - mountPath: /opt/softhsm/tokens
      name: softhsm-tokens
    - mountPath: /opt/softhsm/config.json
      name: softhsm-config
  containers:
    - name: kleidi-provider
      image: ghcr.io/romdalf/kleidi:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: sock
          mountPath: /tmp
        - name: softhsm-config
          mountPath: /opt/softhsm/config.json
        - name: softhsm-tokens
          mountPath: /opt/softhsm/tokens
  volumes:
    - name: sock
      hostPath:
        path: /tmp
    - name: softhsm-config
      hostPath:
        path: /opt/softhsm/config.json
        type: file
    - name: softhsm-tokens
      hostPath:
        path: /opt/softhsm/tokens
        type: DirectoryOrCreate
