---
apiVersion: v1
kind: Pod
metadata:
  name: kleidi-kms-plugin
  namespace: kube-system
  labels:
    tier: control-plane
    component: kleidi-kms-plugin
spec:
  serviceAccount: kleidi-vault-auth
  hostNetwork: true
  containers:
    - name: kleidi-kms-plugin
      image: ghcr.io/beezy-dev/kleidi-kms-plugin:vault-dev
      imagePullPolicy: Always
      args:
        - -provider=hvault
      resources:
        limits:
          cpu: 300m
          memory: 256Mi
      volumeMounts:
        - name: sock
          mountPath: /tmp/kleidi
        - name: kleidi-config
          mountPath: /opt/kleidi/config.json
  volumes:
    - name: sock
      hostPath:
        path: /tmp/kleidi
        type: DirectoryOrCreate
    - name: kleidi-config
      hostPath:
        path: /opt/kleidi/config.json
        type: File
